name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: set arm64
        run: |
          wget https://github.com/strace/strace/releases/download/v5.10/strace-5.10.tar.xz
          tar -xf strace-5.10.tar.xz
          cd strace-5.10/
          ./configure --build x86_64-pc-linux-gnu --host aarch64-linux-gnu LDFLAGS="-static -pthread" --enable-mpers=check
          make
          file strace
          uname -m
