name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: set arm64 1
        run: |
          cd ~/
          git clone -b v3.5.2 https://github.com/google/protobuf.git protobuf
          cd protobuf
          git submodule update --init --recursive
          ./autogen
          mkdir arm64_build
          cd arm64_build
          export CC=aarch64-linux-gnu-gcc \
          export CXX=aarch64-linux-gnu-g++ \
          ../configure --host=aarch64-linux \
          --prefix=$HOME/armnn-devenv/google/arm64_pb_install \
          --with-protoc=$HOME/armnn-devenv/google/x86_64_pb_install/bin/protoc
          make install -j16
          cd ..

          uname -m

      - name: set arm64 2
        run: |
          wget https://github.com/strace/strace/releases/download/v5.10/strace-5.10.tar.xz
          tar -xf strace-5.10.tar.xz
          cd strace-5.10/
          ./configure --build x86_64-pc-linux-gnu --host aarch64-linux-gnu LDFLAGS="-static -pthread" --enable-mpers=check
          make
          file strace
          uname -m
          
          
          
